config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'auditors/login', to: 'auditors#login'
  post 'auditors/login', to: 'auditors#sign_in'

  get 'auditors/individuals/', to: 'auditors#individuals_by_city_report', as: :individuals_by_city_report
  get 'auditors/individuals_by_goods_value', to: 'auditors#individuals_by_goods_value_report'

  root 'auditors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/auditors_controller.rb
class AuditorsController < ApplicationController
	include HTTParty
  base_uri 'https://lion-api.herokuapp.com'

	def index
		@response = self.class.get('/individuals', body: { "access-token" => session[:token], client: session[:client], uid: session[:uid] })
		# connection_verify(@response.headers)
		@individuals = @response.parsed_response
	end

	def login
	end

	def sign_in
		@response = self.class.post('/auth/sign_in', body: { email: params[:email], password: params[:password] } )
		if @response["errors"]
			flash[:error] = @response["errors"][0]
			render :login
		elsif @response.parsed_response["data"]["auditor"]
			session[:token] = @response.headers["access-token"]
			session[:client] = @response.headers["client"]
			session[:uid] = @response.headers["uid"]
			redirect_to root_path
		else
			flash[:error] = "You're not an auditor."
			render :login
		end
	end

	def individuals_by_city_report
    @response = self.class.get("/individuals/#{params[:city]}/by_city", body: { "access-token" => session[:token], client: session[:client], uid: session[:uid] })
  end

  def individuals_by_goods_value_report
  	@response = self.class.get('/individuals/by_goods_value', body: { "access-token" => session[:token], client: session[:client], uid: session[:uid] })
  end

	private
	def connection_verify(headers)
		if headers["access-token"]
			session[:token] = headers["access-token"]
			session[:client] = headers["client"]
			session[:uid] = headers["uid"]
		else
			session[:token] = nil
			session[:client] = nil
			session[:uid] = nil
			redirect_to auditors_login_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auditors_helper.rb
module AuditorsHelper
end

app/views/auditors/index.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Address</th>
      <th>City</th>
      <th>Auditor</th>
    </tr>
  </thead>
  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td><%= individual["name"] %></td>
        <td><%= individual["age"] %></td>
        <td><%= individual["gender"] %></td>
        <td><%= individual["email"] %></td>
        <td><%= individual["address"] %></td>
        <td><%= individual["city"] %></td>
        <td><%= individual["auditor"] ? "Yes" : "No" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/auditors/login.html.erb
<% if flash[:error] %>
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Oh snap!</strong> <%= "#{flash[:error]}" %>
  </div>
<% end %>

<div class="login-panel panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Sign In</h3>
  </div>
  <div class="panel-body">
    <%= form_tag(controller: 'auditors', action: 'sign_in', method: :post) do %>
      <fieldset>
        <div class="form-group">
          <input class="form-control" placeholder="E-mail" name="email" autofocus="">
        </div>
        <div class="form-group">
          <input class="form-control" placeholder="Password" name="password" type="password" value="">
        </div>
        <%= submit_tag "Login", class: "btn btn-success" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>LionAuditor</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<% if session[:token] && session[:client] && session[:uid] %>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Lion Auditor</a>
				</div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li>
							<%= link_to 'Individuals by Goods Value Report', auditors_individuals_by_goods_value_path %>
						</li>
					</ul>

					<%= form_tag(individuals_by_city_report_path, 
												method: :get, class: 'navbar-form navbar-left') do %>
						<div class="form-group">
							<input type="text" class="form-control" placeholder="Individuals By City">
						</div>
						<button type="submit" class="btn btn-default">Submit</button>
					<% end %>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#">Log Out</a></li>
					</ul>
				</div>
			</div>
		</nav>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>